<?php
return array (
  16 => 
  array (
    'modelid' => '16',
    'siteid' => '1',
    'name' => '新闻',
    'description' => '',
    'tablename' => 'yp_news',
    'setting' => 'array (
  \'ismenu\' => \'0\',
  \'meta_title\' => \'中国最全的黄页信息\',
  \'meta_keywords\' => \'中国最全的黄页信息\',
  \'meta_description\' => \'中国最全的黄页信息\',
)',
    'addtime' => '1383493332',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '5',
  ),
  17 => 
  array (
    'modelid' => '17',
    'siteid' => '1',
    'name' => '产品',
    'description' => '',
    'tablename' => 'yp_product',
    'setting' => 'array (
  \'ismenu\' => \'1\',
  \'meta_title\' => \'品牌正品 商城保障\',
  \'meta_keywords\' => \'C2C,购物平台,正品保障\',
  \'meta_description\' => \'亚洲最大网上购物网站——打造的在线B2C购物平台（B2C，Business to Customer）。在商城购物，享受100%正品保障、7天退换货、提供发票的服务。加入商城，将为全新的B2C事业创造更多的奇迹。\',
)',
    'addtime' => '1383493332',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'model_product',
    'list_template' => 'list_product',
    'show_template' => 'show_product',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '5',
  ),
  18 => 
  array (
    'modelid' => '18',
    'siteid' => '1',
    'name' => '商机',
    'description' => '',
    'tablename' => 'yp_buy',
    'setting' => 'array (
  \'ismenu\' => \'1\',
  \'meta_title\' => \'品牌正品 商城保障\',
  \'meta_keywords\' => \'C2C,购物平台,正品保障\',
  \'meta_description\' => \'亚洲最大网上购物网站——打造的在线B2C购物平台（B2C，Business to Customer）。在商城购物，享受100%正品保障、7天退换货、提供发票的服务。加入商城，将为全新的B2C事业创造更多的奇迹。\',
)',
    'addtime' => '1383493332',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'model_buy',
    'list_template' => 'list_buy',
    'show_template' => 'show_buy',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '5',
  ),
);
?>